- name: Print variables
  hosts: web
  vars:
    var_playbook: "var playbook"
    var_whoistheboss: "playbook is the boss"
  tasks:
    - name: Print var_inventory
      ansible.builtin.debug:
        msg: "{{ var_inventory }}"

    - name: Print var_host
      ansible.builtin.debug:
        msg: "{{ var_host }}"

    - name: Print var_playbook
      ansible.builtin.debug:
        msg: "{{ var_playbook }}"

    - name: Print var_survey
      ansible.builtin.debug:
        msg: "{{ var_survey }}"

    - name: Print var_whoistheboss
      ansible.builtin.debug:
        msg: "{{ var_whoistheboss }}"
